apiVersion: v1
kind: Service
metadata:
  name: nlp-ad-classifier-service
spec:
  selector:
    app: nlp-ad-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
